### ISSUE TITLE
io trouble

### ISSUE THREAD

**Issue by Elzor** [EchoTeam/genappup#1]
escript: exception error: bad argument
  in function  io:format/3
     called as io:format(pid(0,24,0),"~p~n",
                         "Despite of the fact some erlang files are changed, current and old versions are the same (1). Should I bump up current app version?")
  in call from genappup:yesno/1 (src/genappup.erl, line 242)
  in call from genappup:version_by_check_result/1 (src/genappup.erl, line 223)
  in call from genappup:prepare_appup/3 (src/genappup.erl, line 47)
  in call from escript:run/2 (escript.erl, line 747)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_it/1 
  in call from init:start_em/1

**Comment by Elzor** [comment]
In 1.0.2 all is good. In master there is this error.

**Comment by juise** [comment]
Hi!

Please, git pull once again, the problem should disappear

**Comment by Elzor** [comment]
Ok. That works.
